### ISSUE TITLE
Support generating model properties

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/kitura-cli#10]
Currently, `kitura create` runs the app generator, and `kitura create <model>` runs the model subgenerator.

We should add support for running the property subgenerator, and as a consequence rework the parameters that `kitura create` supports.

Proposal:

`kitura create` - run the app generator (no change)

`kitura create <name>` - run the app generator specifying a project name

`kitura create --model [name]` - run the model subgenerator optionally specifying a model name

`kitura create --property` - run the property subgenerator

**Comment by ianpartridge** [comment]
@tunniclm does this accurately reflect what we discussed?

**Comment by tunniclm** [comment]
Yes, are you planning on supporting passing down options as well so someone could do `kitura create --skip-build`?

**Comment by ianpartridge** [comment]
Yes. `kitura init` now supports options so you can do `kitura init --skip-build` (that's what the test does). I'll add this to `kitura create` as well.

**Comment by ianpartridge** [comment]
Fixed in https://github.com/IBM-Swift/kitura-cli/pull/14
