### ISSUE TITLE
Object Store uses deprecated 

### ISSUE THREAD

**Issue by icyield** [IBM-Swift/kitura-cli#23]
Object Store option uses  deprecated 
https://github.com/ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-swift.git

Will it be transitioning to Cloud Object Store?
Thanks

**Comment by ianpartridge** [comment]
Hi. We do not currently have plans to release a Swift SDK for IBM Cloud Object Storage. You can use the REST API from your Swift application though - see https://console.bluemix.net/docs/services/cloud-object-storage/api-reference/about-compatibility-api.html#about-the-ibm-cloud-object-storage-api for more information.

**Comment by icyield** [comment]
Easier to say than do reliably, the REST API notes advises .... 

It is not mandatory to use published S3 API SDKs; custom software can leverage the API to integrate directly with Object Storage. However, using published S3 API libraries provide advantages such as authentication/signature generation, automatic retry logic on 5xx errors, and pre-signed url generation. Care must be taken when writing software that uses the API directly to handle transient errors, such as by providing retries with exponential backoff when receiving 503 errors.
