### ISSUE TITLE
Not compatible with Swift 4?

### ISSUE THREAD

**Issue by barksten** [IBM-Swift/kitura-cli#25]
When I do a `kitura init` on version 0.0.9 (installed from the home-brew tap) I get to the interactive scaffolding wizard. I hit enter on every option and I get this error:

> Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
> Target: x86_64-apple-macosx10.9
> Error swiftserver --init 
> 
> Swift version 3 is required for Swift Server Generator.

I was expecting `kitura init` would just create a minimal swift package and `Kitura create` to do all the interactive scaffolding stuff.

**Comment by barksten** [comment]
It turned out that had some old files left from an old installation that caused my problems. I solved it by running `yo` and updated the swift server generator.
Would it be possible to put `npm install -g generator-swiftserver` in the script to do that automatically?

**Comment by ianpartridge** [comment]
Hi @barksten thanks for opening the issue.

If you have an old version of `yo` or `generator-swiftserver` on your system then I recommend you uninstall these via `npm uninstall -g yo generator-swiftserver`.

The CLI doesn't require them to be installed as global node modules.  Instead, it uses `npx` to ensure that the correct version is always used.
