### ISSUE TITLE
Kitura init fails on Linux

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/kitura-cli#42]
Running `kitura init` on Linux (with kitura-cli 0.0.11 or later) generates a broken project.

The `Sources/Generator-Swiftserver-Projects` path is successfully renamed to `Sources/MyProj`, but the `Package.swift` still contains the `Generator-Swiftserver-Projects` placeholders for the target and package name.  This results in a build failure.

`func renameProject()` is trying to execute `sed` commands to perform the project renames with various combinations of casing and hyphenation:
https://github.com/IBM-Swift/kitura-cli/blob/master/kitura-init.js#L101

These seem to succeed on macOS but I'm guessing they are failing (silently) on Linux.

**Comment by TaborKelly** [comment]
I concur, it fails for me with 0.0.12 running on Ubuntu 18.04 with Swift 4.2:
```
tkelly@tabor-xps13:/work/kitura2$ swift --version
Swift version 4.2 (swift-4.2-RELEASE)
Target: x86_64-unknown-linux-gnu
tkelly@tabor-xps13:/work/kitura2$ kitura --version
0.0.12
tkelly@tabor-xps13:/work/kitura2$ kitura init
Creating project...
Project created successfully.
Running `swift build` to build project...
Fetching https://github.com/IBM-Swift/Kitura.git
Fetching https://github.com/IBM-Swift/HeliumLogger.git
Fetching https://github.com/IBM-Swift/CloudEnvironment.git
Fetching https://github.com/RuntimeTools/SwiftMetrics.git
Fetching https://github.com/IBM-Swift/Health.git
Fetching https://github.com/IBM-Swift/Kitura-net.git
Fetching https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Fetching https://github.com/IBM-Swift/KituraContracts.git
Fetching https://github.com/IBM-Swift/TypeDecoder.git
Fetching https://github.com/IBM-Swift/LoggerAPI.git
Fetching https://github.com/IBM-Swift/BlueSocket.git
Fetching https://github.com/IBM-Swift/BlueSSLService.git
Fetching https://github.com/IBM-Swift/BlueSignals.git
Fetching https://github.com/IBM-Swift/OpenSSL.git
Fetching https://github.com/IBM-Swift/Swift-cfenv.git
Fetching https://github.com/IBM-Swift/Configuration.git
Fetching https://github.com/IBM-Swift/FileKit.git
Fetching https://github.com/IBM-Swift/Kitura-WebSocket.git
Fetching https://github.com/RuntimeTools/omr-agentcore
Fetching https://github.com/IBM-Swift/BlueCryptor.git
Completed resolution in 128.84s
Cloning https://github.com/IBM-Swift/Kitura.git
Resolving https://github.com/IBM-Swift/Kitura.git at 2.5.5
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolving https://github.com/IBM-Swift/BlueSocket.git at 1.0.25
Cloning https://github.com/IBM-Swift/Kitura-WebSocket.git
Resolving https://github.com/IBM-Swift/Kitura-WebSocket.git at 2.1.1
Cloning https://github.com/IBM-Swift/TypeDecoder.git
Resolving https://github.com/IBM-Swift/TypeDecoder.git at 1.3.0
Cloning https://github.com/RuntimeTools/SwiftMetrics.git
Resolving https://github.com/RuntimeTools/SwiftMetrics.git at 2.5.0
Cloning https://github.com/IBM-Swift/CloudEnvironment.git
Resolving https://github.com/IBM-Swift/CloudEnvironment.git at 9.0.0
Cloning https://github.com/IBM-Swift/OpenSSL.git
Resolving https://github.com/IBM-Swift/OpenSSL.git at 2.2.0
Cloning https://github.com/IBM-Swift/Configuration.git
Resolving https://github.com/IBM-Swift/Configuration.git at 3.0.1
Cloning https://github.com/IBM-Swift/BlueSSLService.git
Resolving https://github.com/IBM-Swift/BlueSSLService.git at 1.0.25
Cloning https://github.com/IBM-Swift/Health.git
Resolving https://github.com/IBM-Swift/Health.git at 1.0.4
Cloning https://github.com/IBM-Swift/HeliumLogger.git
Resolving https://github.com/IBM-Swift/HeliumLogger.git at 1.7.3
Cloning https://github.com/IBM-Swift/Kitura-net.git
Resolving https://github.com/IBM-Swift/Kitura-net.git at 2.1.2
Cloning https://github.com/IBM-Swift/BlueSignals.git
Resolving https://github.com/IBM-Swift/BlueSignals.git at 1.0.15
Cloning https://github.com/IBM-Swift/FileKit.git
Resolving https://github.com/IBM-Swift/FileKit.git at 0.0.1
Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Resolving https://github.com/IBM-Swift/Kitura-TemplateEngine.git at 2.0.0
Cloning https://github.com/IBM-Swift/LoggerAPI.git
Resolving https://github.com/IBM-Swift/LoggerAPI.git at 1.7.3
Cloning https://github.com/IBM-Swift/Swift-cfenv.git
Resolving https://github.com/IBM-Swift/Swift-cfenv.git at 6.0.2
Cloning https://github.com/IBM-Swift/BlueCryptor.git
Resolving https://github.com/IBM-Swift/BlueCryptor.git at 1.0.20
Cloning https://github.com/IBM-Swift/KituraContracts.git
Resolving https://github.com/IBM-Swift/KituraContracts.git at 1.1.0
Cloning https://github.com/RuntimeTools/omr-agentcore
Resolving https://github.com/RuntimeTools/omr-agentcore at 3.2.4-swift4
'Generator-Swiftserver-Projects' /work/kitura2: error: could not find source files for target(s): Generator-Swiftserver-Projects; use the 'path' property in the Swift 4 manifest to set a custom target path
Failed to complete build.
```

**Comment by shyaml** [comment]
hello, is there any workaround. I have the same problem on ubuntu 17.04

**Comment by christiancompton** [comment]
@shyaml Do you see the same error message as above?

```
error: could not find source files for target(s): Generator-Swiftserver-Projects; use the 'path' property in the Swift 4 manifest to set a custom target path
Failed to complete build.
```

**Comment by shyaml** [comment]
@christiancompton 

i think it is the same error 
 please have a look
==
Successfully built 638734654cff
OK
Creating a container named 
'generatorswiftserverprojects-swift-tools' from that image...
OK
Starting the 'generatorswiftserverprojects-swift-tools' container...
OK
Executing /swift-utils/tools-utils.sh build release command started 
at Tue Feb  5 09:54:34 2019
Current folder: /swift-project
Command: build
Build configuration: release
Build folder: /swift-project/.build-ubuntu
Compiling the project...
Build configuration: release
Fetching https://github.com/IBM-Swift/Swift-cfenv.git
Fetching https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Fetching https://github.com/IBM-Swift/BlueSignals.git
Fetching https://github.com/IBM-Swift/Kitura-net.git
Fetching https://github.com/IBM-Swift/LoggerAPI.git
Fetching https://github.com/IBM-Swift/HeliumLogger.git
Fetching https://github.com/IBM-Swift/Kitura-WebSocket.git
Fetching https://github.com/IBM-Swift/BlueCryptor.git
Fetching https://github.com/IBM-Swift/BlueSocket.git
Fetching https://github.com/IBM-Swift/CloudEnvironment.git
Fetching https://github.com/IBM-Swift/OpenSSL.git
Fetching https://github.com/IBM-Swift/BlueSSLService.git
Fetching https://github.com/IBM-Swift/Kitura.git
Fetching https://github.com/IBM-Swift/Configuration.git
Fetching https://github.com/IBM-Swift/TypeDecoder.git
Fetching https://github.com/IBM-Swift/KituraContracts.git
Fetching https://github.com/IBM-Swift/FileKit.git
Fetching https://github.com/RuntimeTools/omr-agentcore
Fetching https://github.com/RuntimeTools/SwiftMetrics.git
Fetching https://github.com/IBM-Swift/Health.git
Completed resolution in 10.42s
Cloning https://github.com/IBM-Swift/LoggerAPI.git
Resolving https://github.com/IBM-Swift/LoggerAPI.git at 1.8.0
Cloning https://github.com/IBM-Swift/BlueSSLService.git
Resolving https://github.com/IBM-Swift/BlueSSLService.git at 1.0.44
Cloning https://github.com/IBM-Swift/Configuration.git
Resolving https://github.com/IBM-Swift/Configuration.git at 3.0.2
Cloning https://github.com/IBM-Swift/Kitura-net.git
Resolving https://github.com/IBM-Swift/Kitura-net.git at 2.1.6
Cloning https://github.com/IBM-Swift/Swift-cfenv.git
Resolving https://github.com/IBM-Swift/Swift-cfenv.git at 6.0.2
Cloning https://github.com/IBM-Swift/Kitura.git
Resolving https://github.com/IBM-Swift/Kitura.git at 2.6.1
Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Resolving https://github.com/IBM-Swift/Kitura-TemplateEngine.git at 2.0.0
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolving https://github.com/IBM-Swift/BlueSocket.git at 1.0.44
Cloning https://github.com/IBM-Swift/KituraContracts.git
Resolving https://github.com/IBM-Swift/KituraContracts.git at 1.1.1
Cloning https://github.com/RuntimeTools/omr-agentcore
Resolving https://github.com/RuntimeTools/omr-agentcore at 3.2.4-swift4
Cloning https://github.com/IBM-Swift/BlueSignals.git
Resolving https://github.com/IBM-Swift/BlueSignals.git at 1.0.16
Cloning https://github.com/IBM-Swift/FileKit.git
Resolving https://github.com/IBM-Swift/FileKit.git at 0.0.1
Cloning https://github.com/IBM-Swift/OpenSSL.git
Resolving https://github.com/IBM-Swift/OpenSSL.git at 2.2.1
Cloning https://github.com/RuntimeTools/SwiftMetrics.git
Resolving https://github.com/RuntimeTools/SwiftMetrics.git at 2.5.0
Cloning https://github.com/IBM-Swift/BlueCryptor.git
Resolving https://github.com/IBM-Swift/BlueCryptor.git at 1.0.23
Cloning https://github.com/IBM-Swift/CloudEnvironment.git
Resolving https://github.com/IBM-Swift/CloudEnvironment.git at 9.0.0
Cloning https://github.com/IBM-Swift/HeliumLogger.git
Resolving https://github.com/IBM-Swift/HeliumLogger.git at 1.8.0
Cloning https://github.com/IBM-Swift/Health.git
Resolving https://github.com/IBM-Swift/Health.git at 1.0.4
Cloning https://github.com/IBM-Swift/Kitura-WebSocket.git
Resolving https://github.com/IBM-Swift/Kitura-WebSocket.git at 2.1.1
Cloning https://github.com/IBM-Swift/TypeDecoder.git
Resolving https://github.com/IBM-Swift/TypeDecoder.git at 1.3.0
'Generator-Swiftserver-Projects' /swift-project: error: could not find source files for target(s): Generator-Swiftserver-Projects; use the 'path' property in the Swift 4 manifest to set a custom target path
FAILED
Failed to build the application.

Stopping the 'generatorswiftserverprojects-swift-tools' container...
OK
==

**Comment by shyaml** [comment]
@christiancompton 
I have  reinstalled kitura on ubuntu 16.04 on which it was tested but still have the same problem
cloning https://github.com/IBM-Swift/TypeDecoder.git
Resolving https://github.com/IBM-Swift/TypeDecoder.git at 1.3.0
Cloning https://github.com/IBM-Swift/BlueSSLService.git
Resolving https://github.com/IBM-Swift/BlueSSLService.git at 1.0.44
Cloning https://github.com/IBM-Swift/Swift-cfenv.git
Resolving https://github.com/IBM-Swift/Swift-cfenv.git at 6.0.2
'Generator-Swiftserver-Projects' /home/shyam/HelloKitura: error: could not find source files for target(s): Generator-Swiftserver-Projects; use the 'path' property in the Swift 4 manifest to set a custom target path
Failed to complete build.

**Comment by DunnCoding** [comment]
I've opened a [PR](https://github.com/IBM-Swift/kitura-cli/pull/50) to resolve this issue.

**Comment by djones6** [comment]
Merged
