### ISSUE TITLE
Kitura CLI re-write

### ISSUE THREAD

**Issue by DunnCoding** [IBM-Swift/kitura-cli#53]
## Context and Description
Currently the CLI requires npm installed on a users machine to use which isn't ideal for a Swift project. Writing the CLI in Go will prevent that requirement as well as providing more flexibility in our CLI. 

For this we'll be using [Cobra](https://github.com/spf13/cobra) which is a popular Go library for creating CLI applications. 

For this we will have to lose `kitura create` as it still calls out to the generator, but in its current state I feel this is an acceptable loss. 

## Requirements
We obviously do not want to lose any of the core functionality of the CLI, so the minimum requirements are to match the currently functionality. I would however like to add some improvements, a full list follows:

### Required
- [x] kitura init
- [x] kitura init --skip-build
- [x] kitura build
- [x] kitura run
- [x] kitura idt
- [x] kitura sdk
- [x] kitura kit ?
- [x] kitura help

### Optional
- [x] kitura init --dir customDirectoryName
This will enable users to provide a directory name for their Kitura project, rather than having to create a new directory and navigating into it. 

- [x] kitura init --openapi
This will create a Kitura project similar to kitura init but will include OpenAPI support

- [x] kitura init --basic
This will create a basic Kitura project that simply includes Kitura and an example hello world route.

## Tests
We also need to include tests for each build command to ensure projects build successfully, this will mirror the tests we currently have. 

I'll also be including tests for any helper functions we need. 

### macOS
On macOS the CLI app should be available via `brew` like it currently is. The npm installation option will no longer be available. 
 
### Linux
As the npm installation option is no longer available we will need a deployment plan for Linux. A popular choice seems to be hosting the binary in a public location and allow users to `curl` this to install however I will look into what other options are available.

**Comment by DunnCoding** [comment]
Work for this issue is currently located on my public repo: 
https://github.com/ddunn2/kitura-cli-go

Once I have this in a state I'm happy with it, I'll port over to a branch on this repo and open a PR. 

I'm currently implementing `api` and `basic` as flags, as they are simply new commands at the moment, for example: 
`kitura api`
`kitura basic`

I'm also writing tests as I go.

**Comment by DunnCoding** [comment]
I just need to round off the testing suite now. 

The cli written in go has parity with the current cli as far as functionality is concerned.

**Comment by ianpartridge** [comment]
Met with David to discuss this.

Next steps:

1. Package up macOS and cross-compiled Linux binaries. Get @ianpartridge and @kilnerm to test.

**Comment by ianpartridge** [comment]
2. Push a branch to the `kitura-cli` repo containing the new CI.
