### ISSUE TITLE
Add Kitura install to cli (in Go)

### ISSUE THREAD

**Issue by DunnCoding** [IBM-Swift/kitura-cli#55]
Currently every time you want to add a new package to your Kitura project you have to run through the same steps: 
1. Add `.package()` url to Package.swift
2. Add Target name to Package.swift
3. Rebuild project
4. Then if on macOS using Xcode you'll need to generate a new Xcode project

I think it'd be better to make this automated via a command, something like this: 

`kitura install openapi`

Which will update your Package.swift with KituraOpenAPI, rebuild your project and regenerate the xcode project for you if needed.

**Comment by ianpartridge** [comment]
Xcode 11 has support for SPM packages and can do this!!!!!!!!!! (apparently)

**Comment by DunnCoding** [comment]
@ianpartridge Yes it can! 

I've been playing around with it a little over the past couple of days. I don't yet fully understand exactly how it's doing it under the covers, but within Xcode you can add SPM packages to your Xcode project but it doesn't seem to update your Package.swift file? 

So I'm not sure how that'd work on Linux yet, something to test for sure but given the direction SPM and Xcode is taking I don't think we need to bother with this functionality :)
