### ISSUE TITLE
Please explain how to deploy to IBM Cloud Container Service using idt

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/kitura-cli#6]
Please add some information regarding how to deploy a Kitura application scaffolded with kitura-cli to IBM Cloud Container Service.

Even better, please explain how you can point a domain name (e.g. www.example.com) to the container running on the public cloud.

All this is non-obvious, at least to me.

**Comment by ianpartridge** [comment]
Today, you can run `kitura idt` which will install the IBM Cloud Developer Tools on your machine. These tools include Docker, Kubernetes CLI etc.

Once you have those tools you can run `kitura build` to build your project in a local Docker container, and `kitura run` to run in a local Docker container.

To push to the IBM Cloud, you currently have to run `idt deploy`, which can deploy to either a Cloud Foundry buildpack, or the container service. You'll need to do some additional config I think, as I'm not certain that the generator works out-of-the-box with the container service today.

Let me know if you need any more help - perhaps we should take this to Slack?
