### ISSUE TITLE
Please consider an alternative directory structure

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/kitura-cli#7]
```
Sources/MyApp/MyApp ==> Sources/MyApp/my-app-server
Sources/MyApp/Application ==> Sources/MyApp/MyApp
```

This makes more sense to me, what do you think?

**Comment by ianpartridge** [comment]
Thanks for raising the issue. This repo is for issues with the CLI, not the projects it generates. Please could you raise this over at https://github.com/IBM-Swift/generator-swiftserver instead? Thanks!
